# Generated by Django 5.1.1 on 2024-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosApp', '0002_remove_empresa_nombre_empresa_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
            preserve_default=False,
        ),
    ]
