# Generated by Django 5.1.1 on 2024-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosApp', '0003_afiliado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='color_ojos',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='dni',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
    ]
