# Generated by Django 5.1.1 on 2024-09-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosApp', '0004_afiliado_color_ojos_afiliado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('activos', models.IntegerField(blank=True, null=True)),
                ('bajas', models.IntegerField(blank=True, null=True)),
                ('altas', models.IntegerField(blank=True, null=True)),
                ('modif', models.IntegerField(blank=True, null=True)),
                ('cierre', models.DateField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('facturado', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AsociadosApp.empresa')),
            ],
        ),
    ]
