# Generated by Django 5.1.1 on 2024-09-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosApp', '0005_resumenhistorico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='color_ojos',
        ),
    ]
