# Generated by Django 5.1.1 on 2024-09-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosApp', '0006_remove_afiliado_color_ojos'),
        ('AsociadosCfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AsociadosCfg.localidad'),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='nro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
