# Generated by Django 5.1.1 on 2024-10-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomina', '0005_remove_afiliado_facturado_remove_afiliado_importe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=2)),
                ('letra', models.CharField(max_length=1)),
                ('sucursal', models.CharField(max_length=1)),
                ('numero', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('tipo_deudor', models.CharField(max_length=6)),
                ('condicion', models.CharField(max_length=6)),
                ('moneda', models.CharField(max_length=5)),
                ('periodo', models.CharField(max_length=10)),
                ('vencimiento', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomina.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.CharField(max_length=2)),
                ('concepto_codigo', models.CharField(max_length=5)),
                ('concepto_descripcion', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Liquidacion.liquidacioncabecera')),
            ],
        ),
    ]
