# Generated by Django 5.1.1 on 2024-10-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncabecera',
            name='cantidad_afiliados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacioncabecera',
            name='total_liquidado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
