# Generated by Django 5.1.1 on 2024-10-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liquidacion', '0002_liquidacioncabecera_cantidad_afiliados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncabecera',
            name='estado',
            field=models.CharField(default='T', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacioncabecera',
            name='gravada',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
