# Generated by Django 5.1.1 on 2024-09-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AsociadosCfg', '0005_departamento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_fantasia', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11)),
                ('tratamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=11)),
                ('dni', models.CharField(max_length=8)),
                ('sexo', models.CharField(max_length=1)),
                ('nro_afiliado', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('nacimiento', models.DateField()),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('nro', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('facturado', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AsociadosCfg.localidad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomina.empresa')),
            ],
        ),
    ]
