# Generated by Django 5.1.1 on 2024-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='nro_afiliado',
            field=models.CharField(default='9-99999999-99-9', max_length=15),
        ),
    ]
