# Generated by Django 5.1.1 on 2024-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0002_alter_afiliado_nro_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='nro_afiliado',
            field=models.CharField(max_length=15),
        ),
    ]
