# Generated by Django 5.1.1 on 2024-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0003_alter_afiliado_nro_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='nro_afiliado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
