# Generated by Django 5.1.1 on 2024-10-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0004_alter_afiliado_nro_afiliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='facturado',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='periodo',
        ),
    ]
