# Generated by Django 5.1.1 on 2024-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosCfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=1),
        ),
    ]
