# Generated by Django 5.1.1 on 2024-09-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosCfg', '0002_alter_departamento_codigo_alter_localidad_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='codigo',
        ),
    ]
