# Generated by Django 5.1.1 on 2024-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosCfg', '0003_remove_departamento_codigo_remove_localidad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
