# Generated by Django 5.1.1 on 2024-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsociadosCfg', '0004_alter_departamento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
